export const siteConfig = {
  name: 'LycoHana 彼岸花社群',
  shortName: 'LycoHana',
  title: 'LycoHana 彼岸花社群 | ACG、日常與推坑 Discord',
  description:
    'LycoHana 彼岸花是繁體中文的小型 Discord 社群，主要聊 ACG、日常近況、作品推坑、圖片分享。',
  canonicalUrl: 'https://discord.tinyyana.com/',
  locale: 'zh_TW',
  language: 'zh-TW',
  author: 'TinyYana',
  themeColor: '#b83245',
  backgroundColor: '#fbf7ef',
  socialImage: '/Discord_Avatar.jpg',
  socialImageWidth: 128,
  socialImageHeight: 128,
  socialImageType: 'image/jpeg',
  socialImageAlt: 'LycoHana 彼岸花社群的 Discord 頭像',
  keywords: [
    'LycoHana',
    '彼岸花社群',
    'Discord 社群',
    '繁體中文 Discord',
    'ACG',
    '動畫',
    '漫畫',
    '遊戲',
    '推坑',
  ],
  discordInviteUrl: 'https://discord.gg/nMAz72MUxv',
  createdAt: '2021/06/28 22:48',
  createdAtISO: '2021-06-28T22:48:00+08:00',
} as const;
