export const siteConfig = {
  name: '彼岸花社群',
  shortName: '彼岸花社群',
  englishName: 'LycoHana',
  title: '彼岸花社群｜聊 ACG、分享日常的繁中 Discord',
  description:
    '彼岸花社群（LycoHana）是從 2021 年開始的繁中 Discord 小社群。聊動畫漫畫、遊戲音樂，分享圖片與生活近況，偶爾也聊創作、AI 和開發。可以先潛水，遇到有興趣的話題再加入。',
  canonicalUrl: 'https://discord.tinyyana.com/',
  locale: 'zh_TW',
  language: 'zh-TW',
  author: 'TinyYana',
  themeColor: '#b51f32',
  backgroundColor: '#fafafa',
  socialImage: '/images/social-cover.png',
  socialImageWidth: 1200,
  socialImageHeight: 630,
  socialImageType: 'image/png',
  socialImageAlt:
    '彼岸花社群，聊 ACG、分享日常的繁中 Discord，搭配局部彼岸花圖案',
  keywords: [
    'LycoHana',
    '彼岸花社群',
    'Discord 社群',
    '繁體中文 Discord',
    'ACG',
    '動畫',
    '漫畫',
    '遊戲',
    '推坑',
  ],
  discordInviteUrl: 'https://discord.gg/nMAz72MUxv',
  createdAt: '2021/06/28 22:48',
  createdAtISO: '2021-06-28T22:48:00+08:00',
} as const;
